branch-defaults:
  main:
    environment: CloudUtveckling-GB-env
    group_suffix: null
environment-defaults:
  CloudUtveckling-GB-env:
    branch: null
    repository: null
global:
  application_name: CloudUtveckling-GB
  branch: null
  default_ec2_keyname: jensen-server-key
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
