spring:
  application:
    name: cloudutveckling-spring-Gleb-Blumental
  datasource:
    url: jdbc:mysql://localhost:3306/vet_clinic_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 3eqae7trsl4gd1cue823aai5l3
            clientSecret: rb3esf95mmtor5tar6dja5738dfike85123m8s6shgrvhjvvo37
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: VetClinicApp
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_UMdR6Rc8A
            user-name-attribute: username


aws:
  cognito:
    poolId:
    registration:
      clientId: