version: 0.2
os: linux

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Setting JAVA_HOME and PATH...
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
      - export PATH=$JAVA_HOME/bin:$PATH

  build:
    commands:
      - echo "Building application"
      - mvn package -DskipTests
      - echo "Application build complete"

  post_build:
    commands:
      - echo "Post-build phase preparing deployment package"
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - echo "Creating application version"
      - echo `date +%Y-%m-%d-%H-%M-%S` > version.txt
      - cat version.txt
artifacts:
  files:
    - deploy/**/*
    - target/*.jar
  discard-paths: yes

deploy:
  phases:
    pre_deploy:
      commands:
        - echo "Installing AWS Elastic Beanstalk CLI"
        - pip install --upgrade awsebcli
        - eb init -p java --region eu-north-1
    deploy:
      commands:
        - echo "Deploying application to Elastic Beanstalk"
        - eb deploy

