version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - mvn install -DskipTests

  pre_build:
    commands:
      - echo "Preparing build"
      - mvn clean package

  build:
    commands:
      - echo "Building application"
      - mvn package -DskipTests
      - echo "Application build complete"

  post_build:
    commands:
      - echo "Post-build phase: preparing deployment package"
      - mkdir -p deploy
      - cp target/*.jar deploy/

artifacts:
  files:
    - target/*.jar
    - deploy/**
  discard-paths: true

