version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Starting build...
      - export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
      - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - target/*.jar
    -
  discard-paths: yes