version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::332935753543:role/CodeBuildServiceRole

phases:
  install:
    runtime-versions:
      java: corretto22
    commands:
      - echo "Installing dependencies"
      - mvn install -DskipTests

  pre_build:
    commands:
      - echo Starting build...
      - export JAVA_HOME=/usr/lib/jvm/java-22-openjdk
      - export PATH=$JAVA_HOME/bin:$PATH

  build:
    commands:
      - echo "Building application"
      - mvn package -DskipTests
      - echo "Application build complete"

  post_build:
    commands:
      - echo "Post-build phase: preparing deployment package"
      - echo Build complete
      - mkdir -p deploy
      - cp target/*.jar deploy/

artifacts:
  files:
    - target/*.jar
    - deploy/**
  discard-paths: true